* The First Driver
:PROPERTIES:
:CUSTOM_ID: cht:first
:END:
** A Bare Minimum Driver
We are writing a bare minimum RTL8139 driver. It does nothing but announces its existence as a Loadable Kernel Module (LKM). The purpose of writing it is testing whether we can build and run an LKM on the VM.

/File: =src/ch03/rtl8139_driver.c=/
#+attr_latex: :options linenos
#+include: "../src/ch03/rtl8139_driver.c" src c -n
We are going to build it as an out-of-tree KLM. Below is the makefile used to build it on the VM. This is a standard makefile for this purpose. The real complexity hides in the kernel build system.
/File: =src/ch03/Makefile=/
#+include: "../src/ch03/Makefile" src makefile
** Transferring The Program
After creating our first driver on the host computer, we will send it to the VM to build and run. See Section [[#sec:miscellaneous]] for details.

Enter =mkdir ~/rtl8139= on the VM.

1. Copy files in =src/ch03= from the host to =~/rt8139= on the VM via the virtual USB disk.
** Building and Running The Driver
You need to install kernel headers on the VM.

1. Run =uname -r= to be sure that your Debian Sarge VM runs kernel 2.6.8.
2. Enter =sudo apt-get install kernel-headers-2.6.8-4-386= to install kernel headers. The installer may ask you to change to a different DVD ISO file in virt-manager.
3. Build the driver in =~/rtl8139= by =make=.
4. Run it by =sudo insmod rtl8139_driver.ko=. Run =lsmod | grep 8139= to confirm that your driver is loaded. Then remove it by =sudo rmmod rtl8139=.
5. See its prints by =dmesg | tail=. You should see lines like:
   #+begin_src text
     rtl8139_driver: no version for "struct_module" found: kernel tainted.
     rtl8139: Driver module loaded successfully.
     rtl8139: Driver module unloaded.
   #+end_src
   Congratulations! Your first driver in running. The =no version= and =kernel tainted= warnings are normal for our driver.
** Navigating the Source Code
To understand how our bare minimum driver works, we need to read its source code, including the kernel source it uses. We will use =eglot= and =clangd= as a code reading tool. See [[#sec:lsp]] on how to set them up.

There is an issue. Debian Sarge is very old and does not support many LSP utilities like =bear= or modern kernel LSP utilities. To use LSP, we can dry run the driver build and convert it to modern =compile_commands.json=.
1. Create a tarball of the prepared kernel source on the VM.
   #+begin_src bash
     sudo apt-get install kernel-source-2.6.8
   #+end_src
2. Copy =/usr/src/kernel-source-2.6.8.tar.bz2= from the VM to a directory of the host computer and extract it.
3. Run =make clean;make lsp= on the VM to create =build.log= and copy it to the host computer.
4. In =src/scripts/lsp=, run =python parse_26_log.py= to generate =compile_commands.json= which looks like this:
   #+begin_src js
     [
       {
         "directory": "/usr/src/kernel-source-2.6.8",
         "command": "gcc -Wp,-MD,/home/zengxu/rtl8139/.rtl8139_driver.o.d -nostdinc -iwithprefix include -D__KERNEL__ -Iinclude  -Wall -Wstrict-prototypes -Wno-trigraphs -fno-strict-aliasing -fno-common -pipe -msoft-float -mpreferred-stack-boundary=2  -march=i386 -Iinclude/asm-i386/mach-default -Os -fomit-frame-pointer    -DMODULE -DKBUILD_BASENAME=rtl8139_driver -DKBUILD_MODNAME=rtl8139_driver -c -o /home/zengxu/rtl8139/.tmp_rtl8139_driver.o /home/zengxu/rtl8139/rtl8139_driver.c",
         "file": "/home/zengxu/rtl8139/rtl8139_driver.c"
       }
     ]
   #+end_src
5. As this file is based on a build log from the VM, the paths are incorrect, so we need to fix them. In =src/scripts/lsp=, customize and run =paths.sh= to fix the paths. The fixed file looks like:
   #+begin_src js
     [
       {
         "directory": "/home/zengxu/Projects/kernel-source-2.6.8",
         "command": "gcc -Wp,-MD,/home/zengxu/Projects/rtl8139/src/ch03/.rtl8139_driver.o.d -nostdinc -iwithprefix include -D__KERNEL__ -Iinclude  -Wall -Wstrict-prototypes -Wno-trigraphs -fno-strict-aliasing -fno-common -pipe -msoft-float -mpreferred-stack-boundary=2  -march=i386 -Iinclude/asm-i386/mach-default -Os -fomit-frame-pointer    -DMODULE -DKBUILD_BASENAME=rtl8139_driver -DKBUILD_MODNAME=rtl8139_driver -c -o /home/zengxu/Projects/rtl8139/src/ch03/.tmp_rtl8139_driver.o /home/zengxu/Projects/rtl8139/src/ch03/rtl8139_driver.c",
         "file": "/home/zengxu/Projects/rtl8139/src/ch03/rtl8139_driver.c"
       }
     ]
   #+end_src
6. Now you can read the code on the host computer in Emacs.
** (Optional) Navigating The Kernel Code
You may want to navigate the 2.6.8 kernel code with eglot. To do that, we need to build the kernel source on the QEMU VM and then convert it to =compile_commands.json=.
1. Extract the kernel source and build the kernel:
   #+begin_src bash
     cd /usr/src
     sudo tar -jxf kernel-source-2.6.8.tar.bz2
     sudo chown -R zengxu:zengxu kernel-source-2.6.8
     cd kernel-source-2.6.8
     cp /boot/config-2.6.8-4-386 .config
     make oldconfig
     make V=1 -w > build.log
   #+end_src
2. Send =build.log= to the host computer.
3. On the host computer, run =python parse_26_log.py= to generate =compile_commands.json=.
4. Customize and run =paths.sh= to fix paths in =compile_commands.json=.
5. Copy created =compile_commands.json= to the root of the extracted kernel source on the host computer.
6. Copy =.clangd= to the root of the extracted kernel source on the host computer.
** Understanding The Code
This is a bare minimum driver without any advanced functionality besides being a KLM and announcing its existence in =dmesg=. Nonetheless, it is the skeleton of the driver with advanced features. I would highly recommend that you read ULK3, LDD3, and ULNI to understand it fully, especially LDD3.

The two symbols =__init= and =__exit= have special meanings. They indicate that functions =rtl8139_init= and =rtl8139_exit= are put in section =.init.text= and =.exit.text= instead of the standard =.text= for normal code. Those two functions consist of an absolutely minimum driver as they are normally required by any LKM to function.

/File: =include/linux/init.h=/
#+attr_latex: :options linenos,firstnumber=42
#+include: "../../kernel-source-2.6.8/include/linux/init.h" src c -n 42 :lines "42-54"
